apiVersion: v2 # версия api чарта
appVersion: "1.0" # версия приложения внутри чарта
description: A Helm chart for Momo-Store-Backend  # Описание приложения в одном предложении
name: backend # имя чарта
version: 1.2.2 # версия чарта, должна быть по SemVer2 
