  environment:
  replicaCount:
  revisionHistoryLimit:
  image:
    repository:
    pullPolicy:
    tag:
  service:
    type:
    port:
    targetPort:
    nodePort:
  resources:
    limits:
      cpu:
      memory:
    requests:
      cpu:
      memory: