apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: momo-store
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/frontend
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - ../../values/frontend.yaml
  syncPolicy:
    automated: {} 