server:
# Меняем тип сервиса на NodePort
  service:
    nodePort: 30083
    type: NodePort
  # Включаем ингресс, прописываем хост, подсеть, адрес и группу
  ingress:
    annotations:
      ingress.alb.yc.io/subnets: <subnetsId>
      ingress.alb.yc.io/external-ipv4-address: <external ipv4 address>
      ingress.alb.yc.io/group-name: infra-alb
      ingress.alb.yc.io/security-groups: <security group Id's>
      # связь между балансировщиком и argocd – также через https
      ingress.alb.yc.io/transport-security: tls
    enabled: true
    # указываем чтобы использовался https
    https: true
    tls:
    - hosts:
      - prometheus.infra.martsinovskiy.ru
      secretName: yc-certmgr-cert-id-fpqspl3civ9a76nsou7m
    hosts:
        - prometheus.infra.martsinovskiy.ru